### ISSUE TITLE
Compute only subset of SPIs in Calculator

### ISSUE THREAD

**Issue by LuRoe7** [DynamicsAndNeuralSystems/pyspi#4]
First of all: great preprint, great package!! It will facilitate the research at our lab essentially!!!

I was wondering how to tell the Calculator function to compute only a few SPIs that I am interested in in order to save processing time?

Best,
Lukas

**Comment by olivercliff** [comment]
Hi Lukas,

Thank you! I'm working on documentation that illustrates how to use all the toolkit's functionality like this. In the meantime, I'll put some details here.

You can easily use a subset of the SPIs by editing the configuration file, [config.yaml](https://github.com/olivercliff/pyspi/blob/main/pyspi/config.yaml), to only include statistics that you want. I tried to make the names in the configuration file as user-friendly as possible, but if you're unsure of what any of them are, you should be able to cross-reference them with the supplementary material in [the preprint](https://arxiv.org/abs/2201.11941) (or simply ask me).

To make sure you don't override the original `config.yaml`, though, I would probably suggest editing a local copy of the file (details below).

Say you've cloned the repository to `~/toolkits/pyspi`, and you're working in the directory `~/workspace`. First, copy the `config.yaml` file to your working directory:
```
cp ~/toolkits/pyspi/pyspi/config.yaml ~/workspace/myconfig.yaml
```

Once you've got your local version, edit the `myconfig.yaml` file to remove any SPIs you're not interested in. A minimal `myconfig.yaml` might look like the following if you're only interested in computing a covariance matrix using the maximum likelihood estimator:

```
# Basic statistics
.statistics.basic:

  # Covariance
  covariance:

    # Maximum likelihood estimator
    - estimator: EmpiricalCovariance
```

Now, when you instantiate the calculator, instead of using the default `config.yaml`, you can input your bespoke file:

```
from pyspi.calculator import Calculator

calc = Caculator(dataset=dataset,configfile='~/workspace/myconfig.yaml')
calc.compute()
```

**Comment by LuRoe7** [comment]
Thank you! And again: amazing work :)
